on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: temurin
    - uses: sbt/setup-sbt@v1
    - run: sbt -v "compile ; reload ; compile"
